/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.3.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CloudTextRequest
 */
public class CloudTextRequestTest {
    private final CloudTextRequest model = new CloudTextRequest();

    /**
     * Model tests for CloudTextRequest
     */
    @Test
    public void testCloudTextRequest() {
        // TODO: test CloudTextRequest
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'handler'
     */
    @Test
    public void handlerTest() {
        // TODO: test handler
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'jobofferurl'
     */
    @Test
    public void jobofferurlTest() {
        // TODO: test jobofferurl
    }

    /**
     * Test the property 'cvurl'
     */
    @Test
    public void cvurlTest() {
        // TODO: test cvurl
    }

    /**
     * Test the property 'coverletterurl'
     */
    @Test
    public void coverletterurlTest() {
        // TODO: test coverletterurl
    }

    /**
     * Test the property 'texts'
     */
    @Test
    public void textsTest() {
        // TODO: test texts
    }

    /**
     * Test the property 'suggestions'
     */
    @Test
    public void suggestionsTest() {
        // TODO: test suggestions
    }

    /**
     * Test the property 'diversity'
     */
    @Test
    public void diversityTest() {
        // TODO: test diversity
    }

    /**
     * Test the property 'tokenize'
     */
    @Test
    public void tokenizeTest() {
        // TODO: test tokenize
    }

    /**
     * Test the property 'origin'
     */
    @Test
    public void originTest() {
        // TODO: test origin
    }

    /**
     * Test the property 'originaltext'
     */
    @Test
    public void originaltextTest() {
        // TODO: test originaltext
    }

    /**
     * Test the property 'alternativetext'
     */
    @Test
    public void alternativetextTest() {
        // TODO: test alternativetext
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'userEmail'
     */
    @Test
    public void userEmailTest() {
        // TODO: test userEmail
    }

}
