/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CompareTextRequest
 */
public class CompareTextRequestTest {
    private final CompareTextRequest model = new CompareTextRequest();

    /**
     * Model tests for CompareTextRequest
     */
    @Test
    public void testCompareTextRequest() {
        // TODO: test CompareTextRequest
    }

    /**
     * Test the property 'originalText'
     */
    @Test
    public void originalTextTest() {
        // TODO: test originalText
    }

    /**
     * Test the property 'alternativeText'
     */
    @Test
    public void alternativeTextTest() {
        // TODO: test alternativeText
    }

    /**
     * Test the property 'origin'
     */
    @Test
    public void originTest() {
        // TODO: test origin
    }

}
