/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.3.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupdocs.model.HttpStatusCode;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FormalizeTextResponse
 */
public class FormalizeTextResponseTest {
    private final FormalizeTextResponse model = new FormalizeTextResponse();

    /**
     * Model tests for FormalizeTextResponse
     */
    @Test
    public void testFormalizeTextResponse() {
        // TODO: test FormalizeTextResponse
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'formalizeResult'
     */
    @Test
    public void formalizeResultTest() {
        // TODO: test formalizeResult
    }

    /**
     * Test the property 'formalizeResults'
     */
    @Test
    public void formalizeResultsTest() {
        // TODO: test formalizeResults
    }

}
