/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupdocs.model.CloudTextRequest;
import com.groupdocs.model.HealthCheckInfo;
import com.groupdocs.model.Model;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HealthCheckResponse
 */
public class HealthCheckResponseTest {
    private final HealthCheckResponse model = new HealthCheckResponse();

    /**
     * Model tests for HealthCheckResponse
     */
    @Test
    public void testHealthCheckResponse() {
        // TODO: test HealthCheckResponse
    }

    /**
     * Test the property 'initialRequest'
     */
    @Test
    public void initialRequestTest() {
        // TODO: test initialRequest
    }

    /**
     * Test the property 'healthCheckInfo'
     */
    @Test
    public void healthCheckInfoTest() {
        // TODO: test healthCheckInfo
    }

    /**
     * Test the property 'models'
     */
    @Test
    public void modelsTest() {
        // TODO: test models
    }

}
