/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.3.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HealthCheckInfo
 */
public class HealthCheckInfoTest {
    private final HealthCheckInfo model = new HealthCheckInfo();

    /**
     * Model tests for HealthCheckInfo
     */
    @Test
    public void testHealthCheckInfo() {
        // TODO: test HealthCheckInfo
    }

    /**
     * Test the property 'filesProcessorStatus'
     */
    @Test
    public void filesProcessorStatusTest() {
        // TODO: test filesProcessorStatus
    }

    /**
     * Test the property 'paraphrasingStatus'
     */
    @Test
    public void paraphrasingStatusTest() {
        // TODO: test paraphrasingStatus
    }

    /**
     * Test the property 'detectorStatus'
     */
    @Test
    public void detectorStatusTest() {
        // TODO: test detectorStatus
    }

    /**
     * Test the property 'summarizationStatus'
     */
    @Test
    public void summarizationStatusTest() {
        // TODO: test summarizationStatus
    }

    /**
     * Test the property 'gpuInfoStatusCode'
     */
    @Test
    public void gpuInfoStatusCodeTest() {
        // TODO: test gpuInfoStatusCode
    }

    /**
     * Test the property 'gpuInfoMessage'
     */
    @Test
    public void gpuInfoMessageTest() {
        // TODO: test gpuInfoMessage
    }

}
