/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ParaphraseSupportedFormats
 */
public class ParaphraseSupportedFormatsTest {
    /**
     * Model tests for ParaphraseSupportedFormats
     */
    @Test
    public void testParaphraseSupportedFormats() {
        // TODO: test ParaphraseSupportedFormats
    }

}
