/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.3.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupdocs.model.DegreeEnum;
import com.groupdocs.model.FileSavingMode;
import com.groupdocs.model.ParaphraseSupportedFormats;
import com.groupdocs.model.SupportedConversionsFormats;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ParaphraseFileRequest
 */
public class ParaphraseFileRequestTest {
    private final ParaphraseFileRequest model = new ParaphraseFileRequest();

    /**
     * Model tests for ParaphraseFileRequest
     */
    @Test
    public void testParaphraseFileRequest() {
        // TODO: test ParaphraseFileRequest
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'origin'
     */
    @Test
    public void originTest() {
        // TODO: test origin
    }

    /**
     * Test the property 'originalName'
     */
    @Test
    public void originalNameTest() {
        // TODO: test originalName
    }

    /**
     * Test the property 'savingMode'
     */
    @Test
    public void savingModeTest() {
        // TODO: test savingMode
    }

    /**
     * Test the property 'outputFormat'
     */
    @Test
    public void outputFormatTest() {
        // TODO: test outputFormat
    }

    /**
     * Test the property 'diversityDegree'
     */
    @Test
    public void diversityDegreeTest() {
        // TODO: test diversityDegree
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

}
