/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupdocs.model.DegreeEnum;
import com.groupdocs.model.FileSavingMode;
import com.groupdocs.model.TrialSupportedFormats;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SummarizationTrialFileRequest
 */
public class SummarizationTrialFileRequestTest {
    private final SummarizationTrialFileRequest model = new SummarizationTrialFileRequest();

    /**
     * Model tests for SummarizationTrialFileRequest
     */
    @Test
    public void testSummarizationTrialFileRequest() {
        // TODO: test SummarizationTrialFileRequest
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'origin'
     */
    @Test
    public void originTest() {
        // TODO: test origin
    }

    /**
     * Test the property 'originalName'
     */
    @Test
    public void originalNameTest() {
        // TODO: test originalName
    }

    /**
     * Test the property 'savingMode'
     */
    @Test
    public void savingModeTest() {
        // TODO: test savingMode
    }

    /**
     * Test the property 'summarizationDegree'
     */
    @Test
    public void summarizationDegreeTest() {
        // TODO: test summarizationDegree
    }

    /**
     * Test the property 'minLength'
     */
    @Test
    public void minLengthTest() {
        // TODO: test minLength
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

}
