/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupdocs.model.HttpStatusCode;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SummarizationTextResponse
 */
public class SummarizationTextResponseTest {
    private final SummarizationTextResponse model = new SummarizationTextResponse();

    /**
     * Model tests for SummarizationTextResponse
     */
    @Test
    public void testSummarizationTextResponse() {
        // TODO: test SummarizationTextResponse
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'summarizationResult'
     */
    @Test
    public void summarizationResultTest() {
        // TODO: test summarizationResult
    }

    /**
     * Test the property 'summarizationResults'
     */
    @Test
    public void summarizationResultsTest() {
        // TODO: test summarizationResults
    }

}
