/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.11.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.groupdocs.JSON;

/**
 * CloudTextRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-24T16:33:55.576459+03:00[Europe/Moscow]", comments = "Generator version: 7.10.0")
public class CloudTextRequest {
  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  @javax.annotation.Nullable
  private Integer language;

  public static final String SERIALIZED_NAME_HANDLER = "handler";
  @SerializedName(SERIALIZED_NAME_HANDLER)
  @javax.annotation.Nullable
  private String handler;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  @javax.annotation.Nullable
  private String text;

  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  @javax.annotation.Nullable
  private String action;

  public static final String SERIALIZED_NAME_TEXTS = "texts";
  @SerializedName(SERIALIZED_NAME_TEXTS)
  @javax.annotation.Nullable
  private List<String> texts = new ArrayList<>();

  public static final String SERIALIZED_NAME_SUGGESTIONS = "suggestions";
  @SerializedName(SERIALIZED_NAME_SUGGESTIONS)
  @javax.annotation.Nullable
  private Integer suggestions;

  public static final String SERIALIZED_NAME_DIVERSITY = "diversity";
  @SerializedName(SERIALIZED_NAME_DIVERSITY)
  @javax.annotation.Nullable
  private Integer diversity;

  public static final String SERIALIZED_NAME_TOKENIZE = "tokenize";
  @SerializedName(SERIALIZED_NAME_TOKENIZE)
  @javax.annotation.Nullable
  private Boolean tokenize;

  public static final String SERIALIZED_NAME_ORIGIN = "origin";
  @SerializedName(SERIALIZED_NAME_ORIGIN)
  @javax.annotation.Nullable
  private String origin;

  public static final String SERIALIZED_NAME_ORIGINALTEXT = "originaltext";
  @SerializedName(SERIALIZED_NAME_ORIGINALTEXT)
  @javax.annotation.Nullable
  private String originaltext;

  public static final String SERIALIZED_NAME_ALTERNATIVETEXT = "alternativetext";
  @SerializedName(SERIALIZED_NAME_ALTERNATIVETEXT)
  @javax.annotation.Nullable
  private String alternativetext;

  public static final String SERIALIZED_NAME_REQUEST_ID = "requestId";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  @javax.annotation.Nullable
  private String requestId;

  public static final String SERIALIZED_NAME_USER_EMAIL = "userEmail";
  @SerializedName(SERIALIZED_NAME_USER_EMAIL)
  @javax.annotation.Nullable
  private String userEmail;

  public CloudTextRequest() {
  }

  public CloudTextRequest language(@javax.annotation.Nullable Integer language) {
    this.language = language;
    return this;
  }

  /**
   * Language of original text
   * @return language
   */
  @javax.annotation.Nullable
  public Integer getLanguage() {
    return language;
  }

  public void setLanguage(@javax.annotation.Nullable Integer language) {
    this.language = language;
  }


  public CloudTextRequest handler(@javax.annotation.Nullable String handler) {
    this.handler = handler;
    return this;
  }

  /**
   * Defines handler in cloud service
   * @return handler
   */
  @javax.annotation.Nullable
  public String getHandler() {
    return handler;
  }

  public void setHandler(@javax.annotation.Nullable String handler) {
    this.handler = handler;
  }


  public CloudTextRequest text(@javax.annotation.Nullable String text) {
    this.text = text;
    return this;
  }

  /**
   * Text to rewrite
   * @return text
   */
  @javax.annotation.Nullable
  public String getText() {
    return text;
  }

  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }


  public CloudTextRequest action(@javax.annotation.Nullable String action) {
    this.action = action;
    return this;
  }

  /**
   * Rewrite or summarize
   * @return action
   */
  @javax.annotation.Nullable
  public String getAction() {
    return action;
  }

  public void setAction(@javax.annotation.Nullable String action) {
    this.action = action;
  }


  public CloudTextRequest texts(@javax.annotation.Nullable List<String> texts) {
    this.texts = texts;
    return this;
  }

  public CloudTextRequest addTextsItem(String textsItem) {
    if (this.texts == null) {
      this.texts = new ArrayList<>();
    }
    this.texts.add(textsItem);
    return this;
  }

  /**
   * Text array to rewrite
   * @return texts
   */
  @javax.annotation.Nullable
  public List<String> getTexts() {
    return texts;
  }

  public void setTexts(@javax.annotation.Nullable List<String> texts) {
    this.texts = texts;
  }


  public CloudTextRequest suggestions(@javax.annotation.Nullable Integer suggestions) {
    this.suggestions = suggestions;
    return this;
  }

  /**
   * Number of suggested variants, 3 maximum
   * @return suggestions
   */
  @javax.annotation.Nullable
  public Integer getSuggestions() {
    return suggestions;
  }

  public void setSuggestions(@javax.annotation.Nullable Integer suggestions) {
    this.suggestions = suggestions;
  }


  public CloudTextRequest diversity(@javax.annotation.Nullable Integer diversity) {
    this.diversity = diversity;
    return this;
  }

  /**
   * Diversity of text
   * @return diversity
   */
  @javax.annotation.Nullable
  public Integer getDiversity() {
    return diversity;
  }

  public void setDiversity(@javax.annotation.Nullable Integer diversity) {
    this.diversity = diversity;
  }


  public CloudTextRequest tokenize(@javax.annotation.Nullable Boolean tokenize) {
    this.tokenize = tokenize;
    return this;
  }

  /**
   * Should source and target texts be returned in tokenized form
   * @return tokenize
   */
  @javax.annotation.Nullable
  public Boolean getTokenize() {
    return tokenize;
  }

  public void setTokenize(@javax.annotation.Nullable Boolean tokenize) {
    this.tokenize = tokenize;
  }


  public CloudTextRequest origin(@javax.annotation.Nullable String origin) {
    this.origin = origin;
    return this;
  }

  /**
   * for analysis only
   * @return origin
   */
  @javax.annotation.Nullable
  public String getOrigin() {
    return origin;
  }

  public void setOrigin(@javax.annotation.Nullable String origin) {
    this.origin = origin;
  }


  public CloudTextRequest originaltext(@javax.annotation.Nullable String originaltext) {
    this.originaltext = originaltext;
    return this;
  }

  /**
   * Original text
   * @return originaltext
   */
  @javax.annotation.Nullable
  public String getOriginaltext() {
    return originaltext;
  }

  public void setOriginaltext(@javax.annotation.Nullable String originaltext) {
    this.originaltext = originaltext;
  }


  public CloudTextRequest alternativetext(@javax.annotation.Nullable String alternativetext) {
    this.alternativetext = alternativetext;
    return this;
  }

  /**
   * Modified text
   * @return alternativetext
   */
  @javax.annotation.Nullable
  public String getAlternativetext() {
    return alternativetext;
  }

  public void setAlternativetext(@javax.annotation.Nullable String alternativetext) {
    this.alternativetext = alternativetext;
  }


  public CloudTextRequest requestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Get requestId
   * @return requestId
   */
  @javax.annotation.Nullable
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
  }


  public CloudTextRequest userEmail(@javax.annotation.Nullable String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

  /**
   * Get userEmail
   * @return userEmail
   */
  @javax.annotation.Nullable
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(@javax.annotation.Nullable String userEmail) {
    this.userEmail = userEmail;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudTextRequest cloudTextRequest = (CloudTextRequest) o;
    return Objects.equals(this.language, cloudTextRequest.language) &&
        Objects.equals(this.handler, cloudTextRequest.handler) &&
        Objects.equals(this.text, cloudTextRequest.text) &&
        Objects.equals(this.action, cloudTextRequest.action) &&
        Objects.equals(this.texts, cloudTextRequest.texts) &&
        Objects.equals(this.suggestions, cloudTextRequest.suggestions) &&
        Objects.equals(this.diversity, cloudTextRequest.diversity) &&
        Objects.equals(this.tokenize, cloudTextRequest.tokenize) &&
        Objects.equals(this.origin, cloudTextRequest.origin) &&
        Objects.equals(this.originaltext, cloudTextRequest.originaltext) &&
        Objects.equals(this.alternativetext, cloudTextRequest.alternativetext) &&
        Objects.equals(this.requestId, cloudTextRequest.requestId) &&
        Objects.equals(this.userEmail, cloudTextRequest.userEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, handler, text, action, texts, suggestions, diversity, tokenize, origin, originaltext, alternativetext, requestId, userEmail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudTextRequest {\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    handler: ").append(toIndentedString(handler)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    texts: ").append(toIndentedString(texts)).append("\n");
    sb.append("    suggestions: ").append(toIndentedString(suggestions)).append("\n");
    sb.append("    diversity: ").append(toIndentedString(diversity)).append("\n");
    sb.append("    tokenize: ").append(toIndentedString(tokenize)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    originaltext: ").append(toIndentedString(originaltext)).append("\n");
    sb.append("    alternativetext: ").append(toIndentedString(alternativetext)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("language");
    openapiFields.add("handler");
    openapiFields.add("text");
    openapiFields.add("action");
    openapiFields.add("texts");
    openapiFields.add("suggestions");
    openapiFields.add("diversity");
    openapiFields.add("tokenize");
    openapiFields.add("origin");
    openapiFields.add("originaltext");
    openapiFields.add("alternativetext");
    openapiFields.add("requestId");
    openapiFields.add("userEmail");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CloudTextRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CloudTextRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CloudTextRequest is not found in the empty JSON string", CloudTextRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CloudTextRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CloudTextRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("handler") != null && !jsonObj.get("handler").isJsonNull()) && !jsonObj.get("handler").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `handler` to be a primitive type in the JSON string but got `%s`", jsonObj.get("handler").toString()));
      }
      if ((jsonObj.get("text") != null && !jsonObj.get("text").isJsonNull()) && !jsonObj.get("text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("text").toString()));
      }
      if ((jsonObj.get("action") != null && !jsonObj.get("action").isJsonNull()) && !jsonObj.get("action").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `action` to be a primitive type in the JSON string but got `%s`", jsonObj.get("action").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("texts") != null && !jsonObj.get("texts").isJsonNull() && !jsonObj.get("texts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `texts` to be an array in the JSON string but got `%s`", jsonObj.get("texts").toString()));
      }
      if ((jsonObj.get("origin") != null && !jsonObj.get("origin").isJsonNull()) && !jsonObj.get("origin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `origin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("origin").toString()));
      }
      if ((jsonObj.get("originaltext") != null && !jsonObj.get("originaltext").isJsonNull()) && !jsonObj.get("originaltext").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `originaltext` to be a primitive type in the JSON string but got `%s`", jsonObj.get("originaltext").toString()));
      }
      if ((jsonObj.get("alternativetext") != null && !jsonObj.get("alternativetext").isJsonNull()) && !jsonObj.get("alternativetext").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `alternativetext` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alternativetext").toString()));
      }
      if ((jsonObj.get("requestId") != null && !jsonObj.get("requestId").isJsonNull()) && !jsonObj.get("requestId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requestId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requestId").toString()));
      }
      if ((jsonObj.get("userEmail") != null && !jsonObj.get("userEmail").isJsonNull()) && !jsonObj.get("userEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userEmail").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CloudTextRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CloudTextRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CloudTextRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CloudTextRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CloudTextRequest>() {
           @Override
           public void write(JsonWriter out, CloudTextRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CloudTextRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CloudTextRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CloudTextRequest
   * @throws IOException if the JSON string is invalid with respect to CloudTextRequest
   */
  public static CloudTextRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CloudTextRequest.class);
  }

  /**
   * Convert an instance of CloudTextRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

