/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.3.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets FileSavingMode
 */
@JsonAdapter(FileSavingMode.Adapter.class)
public enum FileSavingMode {
  
  FILES("Files"),
  
  ARCHIVE("Archive"),
  
  BOTH("Both");

  private String value;

  FileSavingMode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static FileSavingMode fromValue(String value) {
    for (FileSavingMode b : FileSavingMode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<FileSavingMode> {
    @Override
    public void write(final JsonWriter jsonWriter, final FileSavingMode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public FileSavingMode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return FileSavingMode.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    FileSavingMode.fromValue(value);
  }
}

