/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupdocs.model.HttpStatusCode;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.groupdocs.JSON;

/**
 * SimplifyTextResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-18T14:46:11.043203+03:00[Europe/Moscow]", comments = "Generator version: 7.14.0")
public class SimplifyTextResponse {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private HttpStatusCode status;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nullable
  private String message;

  public static final String SERIALIZED_NAME_SIMPLIFY_RESULT = "simplifyResult";
  @SerializedName(SERIALIZED_NAME_SIMPLIFY_RESULT)
  @javax.annotation.Nullable
  private String simplifyResult;

  public static final String SERIALIZED_NAME_SIMPLIFY_RESULTS = "simplifyResults";
  @SerializedName(SERIALIZED_NAME_SIMPLIFY_RESULTS)
  @javax.annotation.Nullable
  private List<String> simplifyResults;

  public SimplifyTextResponse() {
  }

  public SimplifyTextResponse status(@javax.annotation.Nullable HttpStatusCode status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public HttpStatusCode getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable HttpStatusCode status) {
    this.status = status;
  }


  public SimplifyTextResponse message(@javax.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * Information about process
   * @return message
   */
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }


  public SimplifyTextResponse simplifyResult(@javax.annotation.Nullable String simplifyResult) {
    this.simplifyResult = simplifyResult;
    return this;
  }

  /**
   * Get simplifyResult
   * @return simplifyResult
   */
  @javax.annotation.Nullable
  public String getSimplifyResult() {
    return simplifyResult;
  }

  public void setSimplifyResult(@javax.annotation.Nullable String simplifyResult) {
    this.simplifyResult = simplifyResult;
  }


  public SimplifyTextResponse simplifyResults(@javax.annotation.Nullable List<String> simplifyResults) {
    this.simplifyResults = simplifyResults;
    return this;
  }

  public SimplifyTextResponse addSimplifyResultsItem(String simplifyResultsItem) {
    if (this.simplifyResults == null) {
      this.simplifyResults = new ArrayList<>();
    }
    this.simplifyResults.add(simplifyResultsItem);
    return this;
  }

  /**
   * Get simplifyResults
   * @return simplifyResults
   */
  @javax.annotation.Nullable
  public List<String> getSimplifyResults() {
    return simplifyResults;
  }

  public void setSimplifyResults(@javax.annotation.Nullable List<String> simplifyResults) {
    this.simplifyResults = simplifyResults;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimplifyTextResponse simplifyTextResponse = (SimplifyTextResponse) o;
    return Objects.equals(this.status, simplifyTextResponse.status) &&
        Objects.equals(this.message, simplifyTextResponse.message) &&
        Objects.equals(this.simplifyResult, simplifyTextResponse.simplifyResult) &&
        Objects.equals(this.simplifyResults, simplifyTextResponse.simplifyResults);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, message, simplifyResult, simplifyResults);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimplifyTextResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    simplifyResult: ").append(toIndentedString(simplifyResult)).append("\n");
    sb.append("    simplifyResults: ").append(toIndentedString(simplifyResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("status", "message", "simplifyResult", "simplifyResults"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SimplifyTextResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SimplifyTextResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SimplifyTextResponse is not found in the empty JSON string", SimplifyTextResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SimplifyTextResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SimplifyTextResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        HttpStatusCode.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      if ((jsonObj.get("simplifyResult") != null && !jsonObj.get("simplifyResult").isJsonNull()) && !jsonObj.get("simplifyResult").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `simplifyResult` to be a primitive type in the JSON string but got `%s`", jsonObj.get("simplifyResult").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("simplifyResults") != null && !jsonObj.get("simplifyResults").isJsonNull() && !jsonObj.get("simplifyResults").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `simplifyResults` to be an array in the JSON string but got `%s`", jsonObj.get("simplifyResults").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SimplifyTextResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SimplifyTextResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SimplifyTextResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SimplifyTextResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<SimplifyTextResponse>() {
           @Override
           public void write(JsonWriter out, SimplifyTextResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SimplifyTextResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SimplifyTextResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SimplifyTextResponse
   * @throws IOException if the JSON string is invalid with respect to SimplifyTextResponse
   */
  public static SimplifyTextResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SimplifyTextResponse.class);
  }

  /**
   * Convert an instance of SimplifyTextResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

