/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.groupdocs.ApiException;
import com.groupdocs.model.LanguageInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InfoApi
 */
@Disabled
public class InfoApiTest {

    private final InfoApi api = new InfoApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void infoAvailableLanguagesGetTest() throws ApiException {
        List<LanguageInfo> response = api.infoAvailableLanguagesGet();
        // TODO: test validations
    }

}
