/*
 * GroupDocs.Rewriter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.3.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.groupdocs.ApiException;
import com.groupdocs.model.BaseTextRequest;
import com.groupdocs.model.HealthCheckResponse;
import com.groupdocs.model.SimplifyFileRequest;
import com.groupdocs.model.SimplifyFileResponse;
import com.groupdocs.model.SimplifyOcrRequest;
import com.groupdocs.model.SimplifyTextResponse;
import com.groupdocs.model.SimplifyTrialFileRequest;
import com.groupdocs.model.StatusResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SimplifyApi
 */
@Disabled
public class SimplifyApiTest {

    private final SimplifyApi api = new SimplifyApi();

    /**
     * Simplify document
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void simplifyDocumentPostTest() throws ApiException {
        SimplifyFileRequest simplifyFileRequest = null;
        StatusResponse response = api.simplifyDocumentPost(simplifyFileRequest);
        // TODO: test validations
    }

    /**
     * Return document simplifying status.  Also return URLs for downloading of simplified document if paraphrasig was successful
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void simplifyDocumentRequestIdGetTest() throws ApiException {
        String requestId = null;
        SimplifyFileResponse response = api.simplifyDocumentRequestIdGet(requestId);
        // TODO: test validations
    }

    /**
     * Trial simplify document
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void simplifyDocumentTrialPostTest() throws ApiException {
        SimplifyTrialFileRequest simplifyTrialFileRequest = null;
        StatusResponse response = api.simplifyDocumentTrialPost(simplifyTrialFileRequest);
        // TODO: test validations
    }

    /**
     * Health check for all simplify services.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void simplifyHcGetTest() throws ApiException {
        HealthCheckResponse response = api.simplifyHcGet();
        // TODO: test validations
    }

    /**
     * Simplify scanned image or document
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void simplifyOcrPostTest() throws ApiException {
        SimplifyOcrRequest simplifyOcrRequest = null;
        StatusResponse response = api.simplifyOcrPost(simplifyOcrRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void simplifySupportedConversionsGetTest() throws ApiException {
        String format = null;
        List<String> response = api.simplifySupportedConversionsGet(format);
        // TODO: test validations
    }

    /**
     * Simplify text
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void simplifyTextPostTest() throws ApiException {
        BaseTextRequest baseTextRequest = null;
        StatusResponse response = api.simplifyTextPost(baseTextRequest);
        // TODO: test validations
    }

    /**
     * Return text simplifying status.  Also return simplified text if paraphrasing was successful
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void simplifyTextRequestIdGetTest() throws ApiException {
        String requestId = null;
        SimplifyTextResponse response = api.simplifyTextRequestIdGet(requestId);
        // TODO: test validations
    }

    /**
     * Trial simplify text
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void simplifyTextTrialPostTest() throws ApiException {
        BaseTextRequest baseTextRequest = null;
        StatusResponse response = api.simplifyTextTrialPost(baseTextRequest);
        // TODO: test validations
    }

}
